Adding Secret scanning

diff --git a/.github/workflows/workflow.yml b/.github/workflows/workflow.yml
--- a/.github/workflows/workflow.yml
+++ b/.github/workflows/workflow.yml
@@ -28,6 +28,13 @@ jobs:
       - name: Print Go version
         run: go version
 
-      # Run unit tests.
-      - name: Run unit tests
-        run: go test -v ./...
+      # Run Secret Scanning Tests
+      - name: Run Secret Scanning Tests
+        run: |
+          git secrets --install
+          git secrets --register-aws
+          git secrets --scan
+          if [ $? -eq 0 ]; then
+              echo "git secrets --scan OK"
+          else
+              echo "git secrets --scan FAIL"
